xrdb -merge $HOME/.Xresources

$SCRIPTS_PATH/setkb
$SCRIPTS_PATH/setwp
unclutter &
dunst &
redshift -l 46.5:6.64 -g 0.8 &
$SCRIPTS_PATH/mute on
$SCRIPTS_PATH/lockhook

systemctl --user import-environment DISPLAY
systemctl --user start clipmenud.service

exec i3
