xrdb -merge $HOME/.Xresources

$SCRIPTS_PATH/setkb
$SCRIPTS_PATH/setwp
unclutter &
dunst &
redshift -l 46.5:6.64 -g 0.8 &
$SCRIPTS_PATH/mute on
$SCRIPTS_PATH/lockhook

if which dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi
systemctl --user import-environment DISPLAY XAUTHORITY
systemctl --user start clipmenud.service

exec i3
