#!/bin/sh

option='s'
if [ $# -eq 1 -a $(wc -m <<<"$1") -eq 2 ]
then
	option="$1"
fi

if ! [ -d /tmp/screenshots ]
then
	mkdir /tmp/screenshots
fi

tmpname="$(date +"%Y-%m-%d_%T").png"
tmpname_abs="/tmp/screenshots/$tmpname"

scrot -$option $tmpname_abs
if [ $? -ne 0 ]
then
	exit 1
fi
newname=$(i3-input -P 'filename: ' | grep '^output' | sed -e 's/output = //' -e 's/$/.png/')
if [ "$newname" = ".png" ]
then
	newname=$tmpname
	newname_abs="$HOME/pics/screenshots/$newname"
else
	newname_abs="$HOME/pics/screenshots/$newname"
	if [ -f $newname_abs ]
	then
		echo "This file already exists"
		exit 1
	fi
fi

mv "$tmpname_abs" "$newname_abs"
