#!/bin/bash
export DISPLAY=:0.0
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# low battery in %
LOW_BATTERY=12
# critical battery in %
CRITICAL_BATTERY=6
# display icon
ICON="/usr/share/icons/Adwaita/16x16/status/dialog-warning-symbolic.symbolic.png"

# Getting the actual percentage of each battery
PERC0=$(cat /sys/class/power_supply/BAT0/capacity)
PERC1=$(cat /sys/class/power_supply/BAT1/capacity)
PERC=$(echo "$PERC0*0.5+$PERC1*0.2" | bc)
PERC=${PERC%.*}

if [ -n "$(acpi --ac-adapter | grep "off-line")" ]
then
		echo $PERC
		if [ "$PERC" -lt "$CRITICAL_BATTERY" ]
		then
			waittime=10
			dunstify -u critical -r 30004 -i $ICON "Battery too low, will suspend in $waittime seconds"
			sleep $waittime
			systemctl suspend
		elif [ "$PERC" -lt "$LOW_BATTERY" ]
		then
			dunstify -u critical -r 30004 -i $ICON "Battery is low !!!"
		fi
fi
