#!/bin/sh

#brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
trap 'exit 0' TERM INT
trap "echo startdim >> /home/jules/dim; kill %%" EXIT #"sudo echo $brightness > /sys/class/backlight/intel_backlight/brightness; kill %%" EXIT
#sudo echo 0 > /sys/class/backlight/intel_backlight/brightness
echo "bright0" >> /home/jules/dim
sleep 2147483647 &
wait
