#!/bin/zsh
prefix_file=~

pdfs="$(find ${prefix_file} -type f -name '*.pdf' -not -path "${prefix_file}/.local/*" | sed -e "s,${prefix_file},,")"
configs="$(find ~/.config -type f  -not -path "${prefix_file}/.local/*"| sed -e "s,${prefix_file},,")"
file="$(echo "${pdfs}${configs}" | dmenu -l 10 | sed -e "s, ,\ ,g")"
if ! [ -n "$file" ]
then
	exit
fi
file="${prefix_file}${file}"

xdg-open $file &|
