#!/bin/zsh
cd $HOME
directory=$(pwd)
files=$(fzf -m)
cd -

pdfs=""
multiple_pdfs=""

while read -r file; do
	file="$directory/$file"

	if [ "$(head -c 4 "$file")" = "%PDF" ]; then
		if [ -z "$pdfs" ]; then
			pdfs="$file"
		else
			pdfs="$pdfs $file"
			multiple_pdfs="true"
		fi
	else
		i3-msg exec xdg-open "$file"
	fi
done <<< "$files"

if [ -n "$pdfs" ]; then
	if [ -z "$multiple_pdfs" ]; then
		i3-msg exec zathura $pdfs
	else
		i3-msg exec "tabbed -c zathura "$pdfs" -e"
	fi
fi


