#!/bin/zsh
cd $HOME
directory=$(pwd)
files=$(fzf -m)
cd -

#i3-msg layout default
i=0
while read -r file; do
	#if [ $i -eq 0 ]
	#then
	#	i3-msg split toggle
	#fi
	file="'$file'"
	i3-msg exec xdg-open "$file"
	i+=1
done <<< "$files"

#i3-msg layout tabbed
