#!/bin/python

import json
import subprocess
import re

i3_cmd = 'i3-msg -t get_tree'

def get_layout():
    get_tree = subprocess.Popen(i3_cmd.split(), stdout=subprocess.PIPE)
    stdout = get_tree.communicate()[0]
    try:
        tree = json.loads(stdout)
    except ValueError:
        tree = {}
    return tree

def focused_fullscreen():
    layout = get_layout()
    with open("/home/jules/log", "a") as l:
        match = re.search('{[^{]*"focused":true[^}]*}', layout)
        focused = dict(layout[match.start():match.end()])
        l.write("a", layout, "\n\n", focused)
        #return node['fullscreen_mode'] == 1

if __name__ == '__main__':
    with open("/home/jules/pyi3", "a") as f:
        v = get_layout()
        f.write(type(v))
    focused_fullscreen()
