#!/bin/bash
# Set keyboard layout for thinkpad T460s
# And remap keys as follows for easy access:
# Escape <-> Caps_lock
# ö -> /
# ä -> ~
# altGr+à -> |

setxkbmap -model thinkpad -layout ch -variant fr
xmodmap -e 'keycode 66 = Escape'
xmodmap -e 'keycode 9 = Caps_Lock'

xmodmap -e 'keycode  16 = 7 odiaeresis 7 slash bar seveneighths bar'
xmodmap -e 'keycode  47 = eacute slash eacute odiaeresis bar dead_doubleacute dead_acute'
xmodmap -e 'keycode  48 = agrave asciitilde agrave adiaeresis braceleft
