#!/bin/sh

ls "$2" &>/dev/null
if [ $? -eq 0 ]
then
	echo "File $2 already exits"
	exit 1
fi
if [ $# -ne 2 ]
then
	echo "touchx need the environnement and the file name"
	exit 1
fi
touch "$2"
chmod +x "$2"
echo "#!/bin/$1" > $2
