#!/bin/zsh
# File opener using fzf

prefix_file=~
cd $prefix_file
files=$(fzf -m)
cd -
files=$(printf "%s" "$files" | sed 's/ /\\ /g')

pdfs=$(printf "%s" "$files" | sed '/^.*\.pdf$/!d')
num_pdfs=$(printf "%s" "$files" | wc -l)  # if 1 or 0 -> 1
non_pdfs=$(printf "%s" "$files" | sed -e '/^.*\.pdf$/d')

echo "nonpdfs-> $non_pdfs"
echo "pdfs -> $pdfs"

if [ -n $pdfs ]
then
	echo "num -> $num_pdfs"
	if [ $num_pdfs -gt 1 ]
	then
		echo "multi pdf"
		echo "i3-msg exec tabbed -c zathura $(echo $pdfs | sed "s,^,${prefix_file}\/," | tr '\n' ' ') -e"
		i3-msg exec "tabbed -c zathura $(echo "$pdfs" | sed "s,^,${prefix_file}\/," | tr '\n' ' ') -e"
	elif [ $num_pdfs -eq 1 ]
	then
		echo "pdf"
		i3-msg exec "zathura $(echo "$pdfs" | sed 's/\n/ /')"
	fi
fi

while read -r line
do
	echo "i3-msg exec xdg-open ${prefix_file}/$line"
	i3-msg exec "xdg-open ${prefix_file}/$line"
done <<< "$non_pdfs"

