#!/bin/bash
# Automatic detection and setup of monitors
#
# E.g. it will detect all monitors (from laptop,
# HDMI, etc.), duplicate the screen on all of them
# and setup the sound output to HDMI if present.

format_xrandr="$(xrandr |\
									grep -oE '.*(dis)?connected( primary)?|[0-9]+x[0-9]+[^0-9+].*\+'|\
									sed -r '/\<connected/ {N; s/ *\n/ /}' |\
									sed '/^\s*[0-9]/d' |\
									sed -e 's/\(\S\+\) disconnected/--output \1 --off/' |\
									sed -E 's/([-a-zA-Z0-9]+) connected( primary)? ([0-9]+x[0-9]+).*/--output \1 --mode \3 \2/' |\
									sed 's/primary/--primary/')"

# Checks if multiple monitors with different resolution for the need to scale. In the end, safer to always scale
# in case a scaling has been applied before
# if [ "$(grep -- '--mode \S\+' <<< "$format_xrandr" | sort -u | wc -l)" -gt 1 ]

# Scale and duplicate display
primary_output="$(sed -e '/primary/!d' -e 's/--output \(\S\+\).*/\1/' <<< "$format_xrandr")"
highest_res="$(grep -oP '\d+x\d+' <<< "$format_xrandr" | sort -gr | head -n1)"
format_xrandr="--fb $highest_res $(sed	-e "/--off/!s/$/ --scale-from $highest_res/" \
																				-e "/primary/!s/--mode.*/& --same-as $primary_output/" \
																				<<< "$format_xrandr")"
# NEED TO CHECK THE FOLLOWING
# To put side-by-side instead:
# format_xrandr="$(sed "/primary/!s/--mode \S\+/& --right-of $primary_output/" <<< "$format_xrandr")"

echo xargs -- xrandr '<<<' "$format_xrandr"
xargs -- xrandr <<< "$format_xrandr"
autosound
setwp
