#!/bin/zsh
# Automatic detection and setup of monitors
#
# E.g. it will detect all monitors (from laptop,
# HDMI, etc.), duplicate the screen on all of them
# and setup the sound output to HDMI if present.

format_xrandr="$(xrandr |\
									grep -oE '.*(dis)?connected( primary)?|[0-9]+x[0-9]+[^0-9+].*\+'|\
									sed -r '/\<connected/ {N; s/ *\n/ /}' |\
									sed '/^\s*[0-9]/d' |\
									sed -e 's/\(\S\+\) disconnected/--output \1 --off/' |\
									sed -E 's/([-a-zA-Z0-9]+) connected( primary)? ([0-9]+x[0-9]+).*/--output \1 --mode \3 \2/' |\
									sed 's/primary/--primary/')"

hdmi_present=$(grep -i 'hdmi.*mode' 2>/dev/null <<<$format_xrandr)

if ! [ -z $hdmi_present ]
then
	outhdmi
fi

xargs -- xrandr <<<$format_xrandr
