#!/bin/bash
# Automatic detection and setup of monitors
#
# E.g. it will detect all monitors (from laptop,
# HDMI, etc.), duplicate the screen on all of them
# and setup the sound output to HDMI if present.

format_xrandr="$(xrandr |\
									grep -oE '.*(dis)?connected( primary)?|[0-9]+x[0-9]+[^0-9+].*\+'|\
									sed -r '/\<connected/ {N; s/ *\n/ /}' |\
									sed '/^\s*[0-9]/d' |\
									sed -e 's/\(\S\+\) disconnected/--output \1 --off/' |\
									sed -E 's/([-a-zA-Z0-9]+) connected( primary)? ([0-9]+x[0-9]+).*/--output \1 --mode \3 \2/' |\
									sed 's/primary/--primary/')"

if [ "$(grep -- '--mode \S\+' <<< "$format_xrandr" | sort -u | wc -l)" -gt 1 ]
then
	# Multiple monitors with different resolutions

	# Scale and duplicate display
	primary_output="$(sed -e '/primary/!d' -e 's/--output \(\S\+\).*/\1/' <<< "$format_xrandr")"
	highest_res="$(grep -oP '\d+x\d+' <<< "$format_xrandr" | sort -gr | head -n1)"
	format_xrandr="--fb $highest_res $(sed	-e "s/--primary/& --scale-from $highest_res/" \
																					-e "/primary/!s/--mode.*/& --same-as $primary_output/" \
																					<<< "$format_xrandr")"
	# To put side-by-side instead:
	# format_xrandr="$(sed "/primary/!s/--mode \S\+/& --right-of $primary_output/" <<< "$format_xrandr")"

fi

xargs -- xrandr <<< "$format_xrandr"
autosound
