#!/bin/zsh
trap "exit" INT
set -e

RSYNC_OPTIONS=(-avP --exclude='*.git/*')

backup_path='/mnt/seagate'
dirs_to_sync=('documents' 'downloads/' 'images' 'videos')

echo Backup to $backup_path, containing:
ls --color=always $backup_path

for dir in $dirs_to_sync
do
	output_file="$(mktemp /tmp/backup-script_${dir%/}.XXXX)"
	dir="${dir%/}/"

	echo
	echo Backing up directory "'~/$dir'" to "'$backup_path'":

	echo Running dry run ...
	echo Dry run: > $output_file
	rsync --dry-run "${RSYNC_OPTIONS[@]}" "$HOME/$dir" "$backup_path/$dir" >> $output_file
	echo Dry run available at $output_file.
	if read -q "reply?Show the changes? [y/Y] "
	then
		echo
		vim "$output_file"
	fi

	if read -q "reply?Execute the backup? [y/Y] "
	then
		echo
		echo Launching execution
		echo -e '\n\n\n\n\nReal execution:' >> $output_file
		rsync "${RSYNC_OPTIONS[@]}" "$HOME/$dir" "$backup_path/$dir" | tee -a $output_file

		echo Done with $dir
	else
		echo
		echo Aborting for this directory
	fi
done
