#!/bin/sh
export DISPLAY=:0.0
export XDG_RUNTIME_DIR=/run/user/$(id -u)
ICON="/usr/share/icons/Adwaita/16x16/status/display-brightness-symbolic.symbolic.png"

if [ $1 = '-' ]
then
	xbacklight -dec 5%
elif [ $1 = '+' ]
then
	xbacklight -inc 5%
fi

dunstify -u normal -r 30003 -i $ICON "$(xbacklight -get | sed 's/\..*$//')%"
