#!/bin/sh

actual=$(cat /sys/class/backlight/intel_backlight/brightness)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
new=$(expr $actual + 50)

if [ "$new" -ge "$max" ]
then
	new=$max
fi
echo $new
echo $new > /sys/class/backlight/intel_backlight/brightness
