#!/bin/sh
# updatesl along with supdatesl (dmenu, xorg) for correct automatic permissions?

if [ ! -f $HOME/custom/dots/profile ];then
	echo "Must have custom directory to use this script"
	exit 1
fi
source $HOME/custom/dots/profile
TMP="$(mktemp -d /tmp/arch-install-helper.backup.XXXX)"
echo "Backup at $TMP"

# Get oh-my-zsh
if [ -d $ZSH ]; then
	read -p "Oh-my-zsh folder exists, Delete it? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		rm -r $ZSH
	else
		exit 1
	fi
fi
KEEP_ZSHRC=yes RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ln -fs $DOTS_PATH/mytheme.zsh-theme $ZSH/custom/themes/mytheme.zsh-theme

# Touchpad settings
mv /etc/X11/xorg.conf.d/70-synaptics.conf $TMP
sudo cat /usr/share/X11/xorg.conf.d/70-synaptics.conf $DOTS_PATH/xorg-70-synaptics.conf > /etc/X11/xorg.conf.d/70-synaptics.conf

# Executables
mv /usr/bin/dmenu $TMP
ln -s $SCRIPTS_PATH/dmenu /usr/bin/dmenu


# Config files in home
homenames=('.profile') #'.zprofile' '.xprofile' '.zshrc' '.xinitrc' '.Xressources' '.vimrc' '.gitconfig')
dotsnames=('profile') #'zprofile' 'xprofile' 'zshrc' 'xinitrc' 'xressources' 'vimrc' 'gitconfig')
for i in {1..${#homenames[@]}}; do
	mv $HOME/$homenames $TMP
	ln -s $DOTS_PATH/$dotsnames $HOME/$homenames
	#chown jules:wheel $HOME/$homenames
	if [ $? -eq 0 ]; then
		echo "$homenames -> $dotsnames: Done"
	else
		echo "$homenames -> $dotsnames: Failed"
	fi
done

# Config files in .config
confignames=('archey3/archey3.conf' 'dunst/dunstrc') #'i3/config' 'i3blocks' 'ranger/rc.conf' 'ranger/rifle.conf' 'zathura/zathurarc')
dotsnames=('archey3.conf' 'dunstrc') #'i3config' 'i3blocks' 'ranger-rc.conf' 'ranger-rifle.conf' 'zathurarc')
for i in {1..${#confignames[@]}}; do
	mv $HOME/.config/$confignames $TMP
	ln -s $DOTS_PATH/$dotsnames $HOME/.config/$confignames
	#chown jules:wheel $HOME/.config/$confignames
	if [ $? -eq 0 ]; then
		echo "$confignames -> $dotsnames: Done"
	else
		echo "$confignames -> $dotsnames: Failed"
	fi
done
