#!/bin/zsh
# Fast file launcher for i3 using fzf. Defaults to standalone window
# as a usual file launcher but can also open using vim (useful to open
# files from a terminal) with --vim option. Optionally take a directory
# as argument where it will look for files

source $HOME/.profile

OPENER() { setsid -f o "$1" }
SINGLE_COMMAND_OPEN=false
dir=''
while [[ $# -gt 0 ]]; do
  case $1 in
		--vim)
			OPENER() { vim -p $@ </dev/tty }
			SINGLE_COMMAND_OPEN=true
			# Doesn't work: FZF_OPTS="--preview 'bat --color=always --line-range :500 {}'"
			shift
			;;
		--dragon-drop)
			OPENER() { dragon-drop $@ }
			SINGLE_COMMAND_OPEN=true
			shift
			;;
    -*|--*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
			! [ -z $dir ] && echo 'More than one positional argument passed.' && exit 1
      dir="$1"
      shift
      ;;
  esac
done
[ -z "$dir" ] && dir="$HOME"

cd $dir
prune_patterns=('./\.*' '*/\.git*' './images/*' './musics/*' '.cache/*' '.local/*')
prune_patterns_formatted="$(printf "-path '%s' -prune -o " "${prune_patterns[@]}")"
export FZF_DEFAULT_COMMAND="find . $prune_patterns_formatted -path '*/\.dotfiles/*' -print -o -type f -print 2> /dev/null"

files=$(fzf -m $FZF_OPTS)

[ $? -eq 0 ] || exit 1

mpvs=()
regular_files=()
while read -r file; do
	[ -z "$file" ] && continue
	ftype="$(xdg-mime query filetype $file)"
	file="$file"
	if [[ "$ftype" =~ '^video.*' ]]
	then
		mpvs+="$file"
	else
		regular_files+="$file"
	fi
done <<< "$files"

[ ${#mpvs} -gt 0 ] && i3-msg "exec  mpv ${mpvs[@]}"

if $SINGLE_COMMAND_OPEN
then
	OPENER ${regular_files[@]}
else
	for file in $regular_files
	do
		OPENER "$file"
	done
fi
