#!/bin/zsh
# Fast file launcher for i3 using fzf. Defaults to standalone window
# as a usual file launcher but can also open using vim (useful to open
# files from a terminal) with --vim option. Optionally take a directory
# as argument where it will look for files

source $HOME/.profile

OPENER() { setsid -f o "$1" }
dir=''
while [[ $# -gt 0 ]]; do
  case $1 in
		--vim)
			OPENER() { vim "$1" </dev/tty }
			shift
			;;
    -*|--*)
      echo "Unknown option: $1"
      exit 1
      ;;
    *)
			! [ -z $dir ] && echo 'More than one positional argument passed.' && exit 1
      dir="$1"
      shift
      ;;
  esac
done
[ -z "$dir" ] && dir="$HOME"

cd $dir
export FZF_DEFAULT_COMMAND="find . -path '*/\.git*' -prune -o\
																	 -path 'images/*' -prune -o\
																	 -path 'musics/*' -prune -o\
																	 -type f -print 2> /dev/null"
files=$(fzf -m)

mpvs=()
while read -r file; do
	[ -z "$file" ] && continue
	ftype="$(xdg-mime query filetype $file)"
	file="$file"
	if [[ "$ftype" =~ '^video.*' ]]
	then
		mpvs+="$file"
	else
		OPENER "$file"
	fi
done <<< "$files"

[ ${#mpvs} -gt 0 ] && i3-msg "exec  mpv ${mpvs[@]}"
