#!/bin/zsh
# Fast file launcher for i3 using fzf

source $HOME/.profile

cd $HOME
directory=$(pwd)
export FZF_DEFAULT_COMMAND="find * -path '*/\.*' -prune -o -path 'musics/*' -prune -o -type f -print -o -type l -print 2> /dev/null"
files=$(fzf -m)

mpvs=()
while read -r file; do
	[ -z "$file" ] && continue
	ftype="$(xdg-mime query filetype $file)"
	file="'$file'"
	if [[ "$ftype" =~ '^video.*' ]]
	then
		mpvs+="$file"
	else
		i3-msg "exec  o $HOME/$file"
	fi
done <<< "$files"

i3-msg "exec  mpv ${mpvs[@]}"
