#!/bin/zsh
# Fast file launcher for i3 using fzf

source $HOME/.profile

cd $HOME
directory=$(pwd)
export FZF_DEFAULT_COMMAND="find * -path '*/\.*' -prune -o -path 'musics/*' -prune -o -type f -print -o -type l -print 2> /dev/null"
files=$(fzf -m)
cd -

mpvs=()
while read -r file; do
	[ -z "$file" ] && continue
	file="'$file'"
	#ftype=$(xdg-mime query filetype $file)
	#echo "xdg-mime query filetype $file"
	#if [[ "$ftype" =~ video/.* ]]
	if [[ "$file" =~ .*\.mkv\|.*\.mp4\|.*\.avi ]]
	then
		mpvs+="$file"
	else
		echo i3-msg "exec  o $HOME/$file"
		i3-msg "exec  o $HOME/$file"
	fi
done <<< "$files"

i3-msg "exec  mpv ${mpvs[@]}"
