#!/bin/zsh
source $HOME/.profile

cd $HOME
directory=$(pwd)
files=$(fzf -m)
cd -

mpvs=()
while read -r file; do
	[ -z "$file" ] && continue
	file="'$file'"
	#ftype=$(xdg-mime query filetype $file)
	#echo "xdg-mime query filetype $file"
	#if [[ "$ftype" =~ video/.* ]]
	if [[ "$file" =~ .*\.mkv\|.*\.mp4\|.*\.avi ]]
	then
		mpvs+="$file"
	else
		i3-msg "exec --no-startup-id o $HOME/$file"
	fi
done <<< "$files"

i3-msg "exec --no-startup-id mpv ${mpvs[@]}"
