#!/bin/sh

curr_dir=$(pwd)

while read -r line
do
	cd $line

	# Creation and printing of repo info
	pwd_san=$(pwd | sed s,$EPFL_DIR/,,)
	if [ "$pwd_san" = "$EPFL_DIR" ]
	then
		pwd_san=$(sed 's,.*/\([^/]*\)$,\1,' <<< $pwd_san)
	fi
	printf "\033[0;33m$pwd_san:\n\033[0m"

	git "$@"
done <<< "$(find $EPFL_DIR -type d -name '.git' | sed 's/\.git$//')"

cd $curr_dir
