#!/bin/sh

pipe=0
while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--pipe)
			pipe=1
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
			! [ -z $file ] && echo 'More than one positional argument passed.' && exit 1
      file="$1"
      shift
      ;;
  esac
done

file=$(readlink -f "$file")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

options='--highlight-style=tango -V geometry:margin=1in -s'
if [ $pipe -eq 0 ]
then
	pandoc $options -o "$base.pdf" "$file"
else
	pandoc $options -t pdf "$file"
fi
