#!/bin/sh

default_sink_name="alsa_output.pci-0000_00_1f.3.analog-surround-40\|alsa_output.pci-0000_00_1f.3.analog-stereo"
default_sink="$(pactl list sinks short | grep $default_sink_name | cut -f1)"
active_sink="$(pactl list sinks short | grep RUNNING | cut -f1)"
if [ -z $active_sink ]
then
	sink=$default_sink
else
	sink=$active_sink
fi

pactl set-sink-mute $sink toggle
