#!/bin/zsh
# Script useful to open any file from the terminal so that it
# is independent of it (can close the terminal).

if [ -z $1 ]; then
	setsid -f xdg-open "$(cat -)"
else
	setsid -f xdg-open $1
fi
