#!/bin/sh
# Taken from Luke Smith's confguration at https://github.com/LukeSmithxyz/voidrice
#
# Rotate the files in the current directory. So that for sxiv for example,
# when pressing 'next' the next image comes up.

[ -z "$1" ] && echo "usage: rotdir regex 2>&1" && exit 1
base="$(basename "$1")"
ls "$PWD" | awk -v BASE="$base" 'BEGIN { lines = ""; m = 0; } { if ($0 == BASE) { m = 1; } } { if (!m) { if (lines) { lines = lines"\n"; } lines = lines""$0; } else { print $0; } } END { print lines; }'
