#!/bin/sh

[ -f $HOME/.profile ] && source $HOME/.profile

default="$RICE_PATH/misc/default-wallpaper.jpg"
chosen="$HOME/images/wallpapers/xQO6lJ.png"
if [ -f $chosen ]; then
	feh --no-fehbg --bg-scale $chosen
else
	feh --no-fehbg --bg-scale $default
fi
