#!/bin/sh

[ -f $HOME/.profile ] && source $HOME/.profile

default="$CUSTOM_PATH/misc/default-wallpaper.jpg"
chosen="$HOME/images/wallpapers/fractals/397421.jpg"
if [ -f -chosen ]; then
	feh --no-fehbg --bg-scale $chosen
else
	feh --no-fehbg --bg-scale $default
fi
