#!/bin/bash
# Silent compiler for latex file.
# Provided the name of the latex file (in *.tex format),
# it will compile it and remove all auxiliary files.
# Take an optional second parameter specifying the latex engine.

# Prepare clean on EXIT
cleanup () {
	nfiles_before=$1
	nfiles_after=$(eval "ls -p | grep -Ev '/$|*\.pdf' | wc -l")
	ncreatedfiles=$(($nfiles_after-$nfiles))

	if [ $ncreatedfiles -gt 0 ]; then
		toclean=$(ls -trp | grep -Ev '/$|*\.pdf' | tail -n ${ncreatedfiles})
		echo
		echo Cleaning files: $(sed -E "s/^|$/'/g" <<<$toclean | tr '\n' ' ')
		xargs rm -- <<<$toclean
	fi
}

# Declare available engines and handle optional arguments
ENGINES=('latexmk --pdf' xelatex pdflatex luatex)
interact_opt='-interaction=batchmode'
while [[ $# -gt 0 ]]; do
  case $1 in
    -e|--engine)
      engine="$2"
			[ $engine = 'latexmk' ] && $engine+=' --pdf'
      shift
      shift
      ;;
    -v|--verbose)
      unset interact_opt
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
			! [ -z $texfile ] && echo 'More than one positional argument passed.' && exit 1
      texfile="$1"
      shift
      ;;
  esac
done

if [ -z $engine ]
then
	engine=${ENGINES[0]}
	ENGINES=("${ENGINES[@]:1}")
fi

texfile=$(readlink -f "$texfile")
dir=${texfile%/*}
if ! grep '\\begin{document}' $texfile &>/dev/null
then
	for f in $(find ${texfile%/*/*} -type f -name '*.tex')
	do
		if grep '\\begin{document}' $f &>/dev/null
		then
			texfile="$f"
			dir="${f%/*}"
		fi
	done
fi

cd "$dir"
nfiles=$(eval "ls -p | grep -Ev '/$|*\.pdf' | wc -l")
trap "cleanup '$nfiles'" EXIT

# Compile
texclean -y $texfile
echo "Try to compile with $engine"
eval $engine $interact_opt "$texfile"
[ $? -eq 0 ] && echo -e '\nSuccess' && exit 0

while [ ${#ENGINES[@]} -ne 0 ]
do
	texclean -y $texfile
	echo "Try to compile with ${ENGINES[0]}"
	echo "with 'eval ${ENGINES[0]} $interact_opt "$texfile"'"
	eval ${ENGINES[0]} $interact_opt "$texfile"
	[ $? -eq 0 ] && echo 'Done' && exit 0
	ENGINES=("${ENGINES[@]:1}")
done

# If none successfull, show error
texclean -y $texfile
echo "\nShow error when compiling with $engine:"
$engine "$1"
