#!/usr/bin/env bash
# Got code from https://pastebin.com/DLv1yZR6

BASE_GAPS=-20

# Get current workspace.
workspace=$(i3-msg -t get_workspaces | jq -r '.[] | if .["focused"] then .["name"] else empty end')
# Get current inner gap size. (0 means default)
inner_gaps=$(i3-msg -t get_tree | jq -r 'recurse(.nodes[]) | if .type == "workspace" and .name == "'"$workspace"'" then .gaps.inner else empty end')

if [[ $inner_gaps == $BASE_GAPS ]]; then
	i3-msg "gaps inner current set $I3_DEFAULT_GAPS; gaps outer current set 0"
else
		i3-msg "gaps inner current set 0; gaps outer current set 0"
fi
