#!/bin/zsh
# Script useful to quickly create executable files.
# Usages are:
# touchx filename: create an empty executable filename
# touchx env filename: create an empty executable filename,
#											 with the bash-bang for env already written.

file="${2-$1}"
[ -e "$file" ] && echo "File $2 already exits" && exit 1

touch "$file"
chmod +x "$file"

if [ $# -eq 2 ]
then
	program="$1"
	echo "#!/bin/$program" > "$file"
fi
