#!/bin/sh
export DISPLAY=:0.0
export XDG_RUNTIME_DIR=/run/user/$(id -u)
ICON="/usr/share/icons/Adwaita/16x16/status/audio-volume-high-symbolic.symbolic.png"

default_sink="$(pactl list sinks short | grep alsa_output.pci-0000_00_1f.3.analog-surround-40 | cut -f1)"
active_sink="$(pactl list sinks short | grep RUNNING | cut -f1)"
if [ -z $active_sink ]
then
	sink=$default_sink
else
	sink=$active_sink
fi

echo $sink
pactl set-sink-mute $sink 0
pactl set-sink-volume $sink ${1}5%
# Assuming left and right are the same
vol=$(pactl list sinks | perl -000ne 'if(/#6/){/(Volume:.*)/; print "$1\n"}' | grep --only-matching "\s[0-9]*%" | sed 1q)
if [ $(tr -d '%' <<< $vol) -gt 150 ]
then
	pactl set-sink-volume $sink 150%
	vol="150%"
fi

dunstify -u normal -r 30003 -i $ICON "$vol"
