#!/bin/sh

pid=$(ps aux | grep '/usr/bin/openconnect' | grep -v 'grep' | awk '{print $2}' | sed 's/ \+//g')

if [ ! -z $pid ]
then
	sudo kill $pid
else
	sudo -u jules pass show epfl.ch/gottraux | sudo /usr/bin/openconnect -b vpn.epfl.ch -u gottraux --passwd-on-stdin
fi

